model_path = "src/model/bestv8.pt"
json_key = "proyecto-final-452402-6a01c80ff516.json"
bucket_image_folder = "buffered-keyframes"
bucket_name = "ccp-recommendations-videos"
video_prediction_topic = "video-processing"
recommendations_topic = "recommendations-generation"
email_topic = "email-recommendations"
